### PR TITLE
Maximum withdrawal amount is 99 MYST

### PR DESCRIPTION
**Pull request by tomasmik**
Relates to: https://github.com/mysteriumnetwork/transactor/issues/349

### CODE REVIEW

**Comment by Snawoot** [comment]
What is expected outcome of such limitation? If provider has a friendly transactor w/o such limitation, they will be able to bypass it either way.

**Comment by tomasmik** [comment]
> What is expected outcome of such limitation? If provider has a friendly transactor w/o such limitation, they will be able to bypass it either way.

How? Transactor will also not send a transaction, so there will be nothing to copy. PR for that is coming later.
Also, even if you could bypass this with your own transactor, you're only hurting yourself, so why would you bother doing that.

**Comment by Snawoot** [comment]
@tomasmik

If it's not in the best interest of user, why limit this at all? What is so painful in withdrawal of, let's say, 150 MYST?

**Comment by tomasmik** [comment]
> @tomasmik
> 
> If it's not in the best interest of user, why limit this at all? What is so painful in withdrawal of, let's say, 150 MYST?

Smart contracts actually hard cap the amount, so it wouldn't work anyway.

**Review by Snawoot — APPROVED** [review]

**Review by soffokl — APPROVED** [review]

**Pull request merged**
