### PR TITLE
Revert "Use the latest version of wireguard-go (052af4a8 3/25/2023)"

### PR DESCRIPTION
**Pull request by Zensey**
This reverts commit 80de0274

### CODE REVIEW

**Comment by Snawoot** [comment]
Any explaination why we would want that?

**Comment by Zensey** [comment]
@Snawoot 

> https://github.com/mysteriumnetwork/node/compare/1.20.1...1.20.2
> here was introduced a bug that kills our monitoring agent/superproxy
> I see that wireguard package was updated, but looks like it’s not working as expected
> so monitoring agent creates a lot of connections, disconnects from it, and looks like it’s not releasing properly and the connection cannot be reused anymore

**Review by Snawoot — APPROVED** [review]

**Review by soffokl — COMMENTED** [review]
What do these changes affect? Can we just revert it with no issues?

**Review by soffokl — APPROVED** [review]
I did a test, this seems to be solved the issue.

**Comment by soffokl** [comment]
@Zensey please merge it.

**Pull request merged**
