### PR TITLE
Build supervisor with xgo

### LINKED ISSUE #2314: PackageMacOS fails
Job https://gitlab.com/mysteriumnetwork/node/-/jobs/575171771 fails 

```
ci/packages/build.go:83                  > Building cmd/supervisor/supervisor.go -> myst_supervisor darwin/amd64
 2020-06-01T10:01:05.898 ??? github.com/rs/zerolog@v1.17.2/log.go:403 > exec: go build -ldflags=-w -s -X 'github.com/mysteriumnetwork/node/metadata.BuildBranch=new-wg-setup' -X 'github.com/mysteriumnetwork/node/metadata.BuildCommit=41c24e46' -X 'github.com/mysteriumnetwork/node/metadata.BuildNumber=151483675' -X 'github.com/mysteriumnetwork/node/metadata.Version=0.32.1-1branch-new-wg-set-1' -o /home/gitlab-runner/go/src/github.com/mysteriumnetwork/node/build/myst_supervisor/myst_supervisor cmd/supervisor/supervisor.go
 # github.com/elastic/gosigar
 ../../../../pkg/mod/github.com/elastic/gosigar@v0.10.5/concrete_sigar.go:20:11: cpuUsage.Get undefined (type Cpu has no field or method Get)
 ../../../../pkg/mod/github.com/elastic/gosigar@v0.10.5/concrete_sigar.go:30:13: cpuUsage.Get undefined (type Cpu has no field or method Get)
 ../../../../pkg/mod/github.com/elastic/gosigar@v0.10.5/concrete_sigar.go:49:10: l.Get undefined (type LoadAverage has no field or method Get)
 ../../../../pkg/mod/github.com/elastic/gosigar@v0.10.5/concrete_sigar.go:55:10: m.Get undefined (type Mem has no field or method Get)
 ../../../../pkg/mod/github.com/elastic/gosigar@v0.10.5/concrete_sigar.go:61:10: s.Get undefined (type Swap has no field or method Get)
 ../../../../pkg/mod/github.com/elastic/gosigar@v0.10.5/concrete_sigar.go:67:10: p.Get undefined (type HugeTLBPages has no field or method Get)
 ../../../../pkg/mod/github.com/elastic/gosigar@v0.10.5/concrete_sigar.go:79:11: fd.Get undefined (type FDUsage has no field or method Get)
 ../../../../pkg/mod/github.com/elastic/gosigar@v0.10.5/sigar_darwin_amd64.go:11:12: undefined: sysctlbyname
 Error: running "go build -ldflags=-w -s -X 'github.com/mysteriumnetwork/node/metadata.BuildBranch=new-wg-setup' -X 'github.com/mysteriumnetwork/node/metadata.BuildCommit=41c24e46' -X 'github.com/mysteriumnetwork/node/metadata.BuildNumber=151483675' -X 'github.com/mysteriumnetwork/node/metadata.Version=0.32.1-1branch-new-wg-set-1' -o /home/gitlab-runner/go/src/github.com/mysteriumnetwork/node/build/myst_supervisor/myst_supervisor cmd/supervisor/supervisor.go" failed with exit code 2
```

### PR DESCRIPTION
**Pull request by zolia**
should fix #2314 
Packaging on MacOS is running fine, thats why we missed probably.
We prob need to cross compile anyways.

### CODE REVIEW

**Comment by tadaskay** [comment]
We are already crosscompiling and we don't need xgo for the supervisor. The proper way would be to use a separate go.mod for that sub-project instead of trying to work around go-ethereum quirks (which supervisor does not need at all).

**Comment by vkuznecovas** [comment]
I'm with Tadas on this one. If we use XGO it's going to prolong our build times by quite a lot.

**Comment by zolia** [comment]
We are using xgo for building node atm anyways. I agree that we should migrate to cgo, but there is problem with go-ethereum - again. I suggest to follow this PR to be approved: https://github.com/ethereum/go-ethereum/pull/21041 and bump etherium dependency  then.

For now I suggest to merge as it is.

**Comment by zolia** [comment]
fix by 924532cfbd8896a3d4ecfe12e138dbce41d37a9f and do not depend on go-ethereum in supervisor.  Closing this PR since major refactoring is needed here and best to move to mage format in order to eliminate excessive duplications.

**Pull request closed without merging**
