### PR TITLE
Allow free registration for limited number of providers

### PR DESCRIPTION
**Pull request by vkuznecovas**
Limited free registrations for providers.

### CODE REVIEW

**Review by Snawoot — APPROVED** [review]

**Review by mdomasevicius — APPROVED** [review]

**Comment by Snawoot** [comment]
@vkuznecovas Can you please show a server side implementation for this method? Just curious about some details.

**Comment by vkuznecovas** [comment]
> @vkuznecovas Can you please show a server side implementation for this method? Just curious about some details.

https://github.com/mysteriumnetwork/transactor/pull/305

**Comment by Snawoot** [comment]
@vkuznecovas nice, thanks! just was concerned about limits a little.

**Comment by vkuznecovas** [comment]
> @vkuznecovas nice, thanks! just was concerned about limits a little.

any time :)

**Pull request merged**
