### PR TITLE
abuse.html for exit nodes

### PR DESCRIPTION
**Pull request by KFDCompiled**
Adapted from tor:

[abuse.txt](https://github.com/MysteriumNetwork/node/files/1027983/abuse.txt)

### CODE REVIEW

**Comment by newfulluser** [comment]
Noob question, where is the abuse.html file? I can only see the tor version

**Comment by shroomist** [comment]
is this still relevant? @ignasbernotas

**Comment by Waldz** [comment]
@cvl, did you took abuse.txt to your notes?

**Comment by cvl** [comment]
Thanks for the initiative.
Please do not publish legal materials without consulting legal team.

**Comment by Waldz** [comment]
I am deleting PR, because it has no code changes. 
But thanks @KFDCompiled, noted your proposal.

**Pull request closed without merging**
